// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPmtVJbw0AGSowGpDfR0-E4BBxeniiGtM',
    appId: '1:508221527098:web:214ff5ee97da5a0f7e5103',
    messagingSenderId: '508221527098',
    projectId: 'find-your-mate-739b3',
    authDomain: 'find-your-mate-739b3.firebaseapp.com',
    storageBucket: 'find-your-mate-739b3.appspot.com',
    measurementId: 'G-LZ6VLJJL52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcaHwztKj_S3BMgEL6VPmnMFTdXx6obbw',
    appId: '1:508221527098:android:08478003180680617e5103',
    messagingSenderId: '508221527098',
    projectId: 'find-your-mate-739b3',
    storageBucket: 'find-your-mate-739b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzHiFsRAOgr2dlIYJ_ybFhcE1YaRDp9eI',
    appId: '1:508221527098:ios:4e8c8854b98f5ad77e5103',
    messagingSenderId: '508221527098',
    projectId: 'find-your-mate-739b3',
    storageBucket: 'find-your-mate-739b3.appspot.com',
    iosClientId: '508221527098-d2c814kj1bebd8eaon14vo34e1uinnji.apps.googleusercontent.com',
    iosBundleId: 'com.example.findyourmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzHiFsRAOgr2dlIYJ_ybFhcE1YaRDp9eI',
    appId: '1:508221527098:ios:3d2071738cb8444f7e5103',
    messagingSenderId: '508221527098',
    projectId: 'find-your-mate-739b3',
    storageBucket: 'find-your-mate-739b3.appspot.com',
    iosClientId: '508221527098-uclofd0rusvf8sggvtia0qc6n5078gue.apps.googleusercontent.com',
    iosBundleId: 'com.example.findyourmate.RunnerTests',
  );
}
